#  Copyright (c) 2022 Kokhaviel.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

from utils import checkJsonNullValue


class Bedwars:

    def __init__(self, json):
        self.cosmetics = checkJsonNullValue(eval(json), 'packages')
        self.experience = checkJsonNullValue(eval(json), 'Experience')
        self.bedwars_boxes = checkJsonNullValue(eval(json), 'bedwars_boxes')
        self.chest_history = checkJsonNullValue(eval(json), 'chest_history_new')
        self.active_island_topper = checkJsonNullValue(eval(json), 'activeIslandTopper')
        self.active_glyph = checkJsonNullValue(eval(json), 'activeGlyph')
        self.final_deaths = checkJsonNullValue(eval(json), 'final_deaths_bedwars')
        self.gold_collected = checkJsonNullValue(eval(json), 'gold_resources_collected_bedwars')
        self.diamond_collected = checkJsonNullValue(eval(json), 'diamond_resources_collected_bedwars')
        self.deaths = checkJsonNullValue(eval(json), 'deaths_bedwars')
        self.void_deaths = checkJsonNullValue(eval(json), 'void_deaths_bedwars')
        self.resources_collected = checkJsonNullValue(eval(json), 'resources_collected_bedwars')
        self.coins = checkJsonNullValue(eval(json), 'coins')
        self.games_played = checkJsonNullValue(eval(json), 'games_played_bedwars')
        self.beds_lost = checkJsonNullValue(eval(json), 'beds_lost_bedwars')
        self.void_final_deaths = checkJsonNullValue(eval(json), 'void_final_deaths_bedwars')
        self.losses = checkJsonNullValue(eval(json), 'losses_bedwars')
        self.items_purchased = checkJsonNullValue(eval(json), 'items_purchased_bedwars')
        self.final_kills = checkJsonNullValue(eval(json), 'final_kills_bedwars')
        self.iron_collected = checkJsonNullValue(eval(json), 'iron_resources_collected_bedwars')
        self.beds_broken = checkJsonNullValue(eval(json), 'beds_broken_bedwars')
        self.winstreak = checkJsonNullValue(eval(json), 'winstreak')
        self.void_kills = checkJsonNullValue(eval(json), 'void_kills_bedwars')
        self.kills = checkJsonNullValue(eval(json), 'kills_bedwars')
        self.void_final_kills = checkJsonNullValue(eval(json), 'void_final_kills_bedwars')
        self.wins = checkJsonNullValue(eval(json), 'wins_bedwars')
        self.emerald_collected = checkJsonNullValue(eval(json), 'emerald_resources_collected_bedwars')
        self.active_death_cry = checkJsonNullValue(eval(json), 'activeDeathCry')
        self.active_projectile_trail = checkJsonNullValue(eval(json), 'activeProjectileTrail')
        self.active_sprays = checkJsonNullValue(eval(json), 'activeSprays')
        self.spray_glyph_field = checkJsonNullValue(eval(json), 'spray_glyph_field')
        self.fall_kills = checkJsonNullValue(eval(json), 'fall_kills_bedwars')
        self.fall_deaths = checkJsonNullValue(eval(json), 'fall_deaths_bedwars')
        self.projectile_deaths = checkJsonNullValue(eval(json), 'projectile_deaths_bedwars')
        self.active_npc_skin = checkJsonNullValue(eval(json), 'activeNPCSkin')
        self.active_victory_dance = checkJsonNullValue(eval(json), 'activeVictoryDance')
        self.active_kill_message = checkJsonNullValue(eval(json), 'activeKillMessages')
        self.fall_final_kills = checkJsonNullValue(eval(json), 'fall_final_kills_bedwars')
        self.fall_final_kills = checkJsonNullValue(eval(json), 'active_kill_effect')
        self.shop_favourite_1 = checkJsonNullValue(eval(json), 'favourites_1')
        self.projectile_final_deaths = checkJsonNullValue(eval(json), 'projectile_final_deaths_bedwars')
        self.projectile_kills = checkJsonNullValue(eval(json), 'projectile_kills_bedwars')
        self.fall_final_deaths = checkJsonNullValue(eval(json), 'fall_final_deaths_bedwars')
        self.projectile_final_kills = checkJsonNullValue(eval(json), 'projectile_final_kills_bedwars')
        self.shop_favourite_2 = checkJsonNullValue(eval(json), 'favourites_2')
        self.selected_ultimate = checkJsonNullValue(eval(json), 'selected_ultimate')
        self.permanent_items_purchased = checkJsonNullValue(eval(json), 'permanent_items_purchased_bedwars')

        self.solo_beds_lost = checkJsonNullValue(eval(json), 'eight_one_beds_lost_bedwars')
        self.solo_final_deaths = checkJsonNullValue(eval(json), 'eight_one_final_deaths_bedwars')
        self.solo_deaths = checkJsonNullValue(eval(json), 'eight_one_deaths_bedwars')
        self.solo_void_deaths = checkJsonNullValue(eval(json), 'eight_one_void_deaths_bedwars')
        self.solo_games_played = checkJsonNullValue(eval(json), 'eight_one_games_played_bedwars')
        self.solo_final_kills = checkJsonNullValue(eval(json), 'eight_one_final_kills_bedwars')
        self.solo_beds_broken = checkJsonNullValue(eval(json), 'eight_one_beds_broken_bedwars')
        self.solo_permanent_items_purchased = checkJsonNullValue(eval(json), 'eight_one_permanent_items_purchased_bedwars')
        self.solo_projectile_final_kills = checkJsonNullValue(eval(json), 'eight_one_projectile_final_kills_bedwars')
        self.solo_losses = checkJsonNullValue(eval(json), 'eight_one_losses_bedwars')
        self.solo_iron_collected = checkJsonNullValue(eval(json), 'eight_one_iron_resources_collected_bedwars')
        self.solo_diamond_collected = checkJsonNullValue(eval(json), 'eight_one_diamond_resources_collected_bedwars')
        self.solo_void_final_deaths = checkJsonNullValue(eval(json), 'eight_one_void_final_deaths_bedwars')
        self.solo_resources_collected = checkJsonNullValue(eval(json), 'eight_one_resources_collected_bedwars')
        self.solo_gold_collected = checkJsonNullValue(eval(json), 'eight_one_gold_resources_collected_bedwars')
        self.solo_void_kills = checkJsonNullValue(eval(json), 'eight_one_void_kills_bedwars')
        self.solo_void_final_kills = checkJsonNullValue(eval(json), 'eight_one_void_final_kills_bedwars')
        self.solo_kills = checkJsonNullValue(eval(json), 'eight_one_kills_bedwars')
        self.solo_emerald_collected = checkJsonNullValue(eval(json), 'eight_one_emerald_resources_collected_bedwars')
        self.solo_wins = checkJsonNullValue(eval(json), 'eight_one_wins_bedwars')
        self.solo_fall_final_deaths = checkJsonNullValue(eval(json), 'eight_one_fall_final_deaths_bedwars')
        self.solo_fall_final_kills = checkJsonNullValue(eval(json), 'eight_one_fall_final_kills_bedwars')
        self.solo_fall_kills = checkJsonNullValue(eval(json), 'eight_one_fall_kills_bedwars')
        self.solo_projectile_deaths = checkJsonNullValue(eval(json), 'eight_one_projectile_deaths_bedwars')
        self.solo_winstreak = checkJsonNullValue(eval(json), 'eight_one_winstreak')
        self.solo_fall_deaths = checkJsonNullValue(eval(json), 'eight_one_fall_deaths_bedwars')

        self.double_void_deaths = checkJsonNullValue(eval(json), 'eight_two_void_deaths_bedwars')
        self.double_resources_collected = checkJsonNullValue(eval(json), 'eight_two_resources_collected_bedwars')
        self.double_kills = checkJsonNullValue(eval(json), 'eight_two_kills_bedwars')
        self.double_iron_collected = checkJsonNullValue(eval(json), 'eight_two_iron_resources_collected_bedwars')
        self.double_void_kills = checkJsonNullValue(eval(json), 'eight_two_void_kills_bedwars')
        self.double_final_deaths = checkJsonNullValue(eval(json), 'eight_two_final_deaths_bedwars')
        self.double_void_final_deaths = checkJsonNullValue(eval(json), 'eight_two_void_final_deaths_bedwars')
        self.double_deaths = checkJsonNullValue(eval(json), 'eight_two_void_final_deaths_bedwars')
        self.double_games_played = checkJsonNullValue(eval(json), 'eight_two_games_played_bedwars')
        self.double_items_purchased = checkJsonNullValue(eval(json), 'eight_two_items_purchased_bedwars')
        self.double_beds_lost = checkJsonNullValue(eval(json), 'eight_two_beds_lost_bedwars')
        self.double_gold_collected = checkJsonNullValue(eval(json), 'eight_two_gold_resources_collected_bedwars')
        self.double_losses = checkJsonNullValue(eval(json), 'eight_two_losses_bedwars')
        self.double_final_kills = checkJsonNullValue(eval(json), 'eight_two_final_kills_bedwars')
        self.double_diamonds_collected = checkJsonNullValue(eval(json), 'eight_two_diamond_resources_collected_bedwars')
        self.double_emerald_collected = checkJsonNullValue(eval(json), 'eight_two_emerald_resources_collected_bedwars')
        self.double_beds_broken = checkJsonNullValue(eval(json), 'eight_two_beds_broken_bedwars')
        self.double_wins = checkJsonNullValue(eval(json), 'eight_two_wins_bedwars')
        self.double_void_final_kills = checkJsonNullValue(eval(json), 'eight_two_void_final_kills_bedwars')
        self.double_fall_deaths = checkJsonNullValue(eval(json), 'eight_two_fall_deaths_bedwars')
        self.double_projectile_deaths = checkJsonNullValue(eval(json), 'eight_two_projectile_deaths_bedwars')
        self.double_fall_kills = checkJsonNullValue(eval(json), 'eight_two_fall_kills_bedwars')
        self.double_projectile_final_kills = checkJsonNullValue(eval(json), 'eight_two_projectile_final_kills_bedwars')
        self.double_fall_final_kills = checkJsonNullValue(eval(json), 'eight_two_fall_final_kills_bedwars')
        self.double_fall_final_deaths = checkJsonNullValue(eval(json), 'eight_two_fall_final_deaths_bedwars')
        self.double_projectile_final_deaths = checkJsonNullValue(eval(json), 'eight_two_projectile_final_deaths_bedwars')
        self.double_winstreak = checkJsonNullValue(eval(json), 'eight_two_winstreak')
        self.double_projectile_kills = checkJsonNullValue(eval(json), 'eight_two_projectile_kills_bedwars')
        self.double_permanent_items_purchased = checkJsonNullValue(eval(json), 'eight_two_permanent_items_purchased_bedwars')

        self.three_void_final_kills = checkJsonNullValue(eval(json), 'four_three_void_final_kills_bedwars')
        self.three_void_kills = checkJsonNullValue(eval(json), 'four_three_void_kills_bedwars')
        self.three_iron_collected = checkJsonNullValue(eval(json), 'four_three_iron_resources_collected_bedwars')
        self.three_games_played = checkJsonNullValue(eval(json), 'four_three_games_played_bedwars')
        self.three_void_deaths = checkJsonNullValue(eval(json), 'four_three_void_deaths_bedwars')
        self.three_beds_lost = checkJsonNullValue(eval(json), 'four_three_beds_lost_bedwars')
        self.three_gold_collected = checkJsonNullValue(eval(json), 'four_three_gold_resources_collected_bedwars')
        self.three_deaths = checkJsonNullValue(eval(json), 'four_three_deaths_bedwars')
        self.three_beds_broken = checkJsonNullValue(eval(json), 'four_three_beds_broken_bedwars')
        self.three_losses = checkJsonNullValue(eval(json), 'four_three_losses_bedwars')
        self.three_diamonds_collected = checkJsonNullValue(eval(json), 'four_three_diamond_resources_collected_bedwars')
        self.three_final_kills = checkJsonNullValue(eval(json), 'four_three_final_kills_bedwars')
        self.three_items_purchased = checkJsonNullValue(eval(json), 'four_three_items_purchased_bedwars')
        self.three_kills = checkJsonNullValue(eval(json), 'four_three_kills_bedwars')
        self.three_final_deaths = checkJsonNullValue(eval(json), 'four_three_final_deaths_bedwars')
        self.three_resources_collected = checkJsonNullValue(eval(json), 'four_three_resources_collected_bedwars')
        self.three_emerald_collected = checkJsonNullValue(eval(json), 'four_three_emerald_resources_collected_bedwars')
        self.three_void_final_deaths = checkJsonNullValue(eval(json), 'four_three_void_final_deaths_bedwars')
        self.three_wins = checkJsonNullValue(eval(json), 'four_three_wins_bedwars')
        self.three_projectile_deaths = checkJsonNullValue(eval(json), 'four_three_projectile_deaths_bedwars')
        self.three_fall_kills = checkJsonNullValue(eval(json), 'four_three_fall_kills_bedwars')
        self.three_projectile_final_kills = checkJsonNullValue(eval(json), 'four_three_projectile_final_kills_bedwars')
        self.three_fall_final_kills = checkJsonNullValue(eval(json), 'four_three_fall_final_kills_bedwars')
        self.three_fall_deaths = checkJsonNullValue(eval(json), 'four_three_fall_deaths_bedwars')
        self.three_projectile_kills = checkJsonNullValue(eval(json), 'four_three_projectile_kills_bedwars')
        self.three_fall_final_deaths = checkJsonNullValue(eval(json), 'four_three_fall_final_deaths_bedwars')
        self.three_winstreak = checkJsonNullValue(eval(json), 'four_three_winstreak')
        self.three_permanent_items_puchased = checkJsonNullValue(eval(json), 'four_three_permanent_items_purchased_bedwars')

        self.four_void_kills = checkJsonNullValue(eval(json), 'four_four_void_kills_bedwars')
        self.four_kills = checkJsonNullValue(eval(json), 'four_four_kills_bedwars')
        self.four_final_deaths = checkJsonNullValue(eval(json), 'four_four_final_deaths_bedwars')
        self.four_gold_collected = checkJsonNullValue(eval(json), 'four_four_gold_resources_collected_bedwars')
        self.four_beds_lost = checkJsonNullValue(eval(json), 'four_four_beds_lost_bedwars')
        self.four_losses = checkJsonNullValue(eval(json), 'four_four_losses_bedwars')
        self.four_iron_collected = checkJsonNullValue(eval(json), 'four_four_iron_resources_collected_bedwars')
        self.four_games_played = checkJsonNullValue(eval(json), 'four_four_games_played_bedwars')
        self.four_resources_collected = checkJsonNullValue(eval(json), 'four_four_resources_collected_bedwars')
        self.four_items_collected = checkJsonNullValue(eval(json), 'four_four_items_purchased_bedwars')
        self.four_wins = checkJsonNullValue(eval(json), 'four_four_wins_bedwars')
        self.four_deaths = checkJsonNullValue(eval(json), 'four_four_deaths_bedwars')
        self.four_diamonds_collected = checkJsonNullValue(eval(json), 'four_four_diamond_resources_collected_bedwars')
        self.four_void_final_kills = checkJsonNullValue(eval(json), 'four_four_void_final_kills_bedwars')
        self.four_void_deaths = checkJsonNullValue(eval(json), 'four_four_void_deaths_bedwars')
        self.four_final_kills = checkJsonNullValue(eval(json), 'four_four_final_kills_bedwars')
        self.four_emerald_collected = checkJsonNullValue(eval(json), 'four_four_emerald_resources_collected_bedwars')
        self.four_void_final_deaths = checkJsonNullValue(eval(json), 'four_four_void_final_deaths_bedwars')
        self.four_projectile_kills = checkJsonNullValue(eval(json), 'four_four_projectile_kills_bedwars')
        self.four_fall_kills = checkJsonNullValue(eval(json), 'four_four_fall_kills_bedwars')
        self.four_fall_deaths = checkJsonNullValue(eval(json), 'four_four_fall_deaths_bedwars')
        self.four_beds_broken = checkJsonNullValue(eval(json), 'four_four_beds_broken_bedwars')
        self.four_projectile_deaths = checkJsonNullValue(eval(json), 'four_four_projectile_deaths_bedwars')
        self.four_fall_final_kills = checkJsonNullValue(eval(json), 'four_four_fall_final_kills_bedwars')
        self.four_projectile_final_deaths = checkJsonNullValue(eval(json), 'four_four_projectile_final_deaths_bedwars')
        self.four_fall_final_deaths = checkJsonNullValue(eval(json), 'four_four_fall_final_deaths_bedwars')
        self.four_winstreak = checkJsonNullValue(eval(json), 'four_four_winstreak')
        self.four_projectile_final_kills = checkJsonNullValue(eval(json), 'four_four_projectile_final_kills_bedwars')
        self.four_permanent_items_purchased = checkJsonNullValue(eval(json), 'four_four_permanent_items_purchased_bedwars')

        self.two_four_winstreak = checkJsonNullValue(eval(json), 'two_four_winstreak')
        self.two_four_deaths = checkJsonNullValue(eval(json), 'two_four_deaths_bedwars')
        self.two_four_games_played = checkJsonNullValue(eval(json), 'two_four_games_played_bedwars')
        self.two_four_gold_collected = checkJsonNullValue(eval(json), 'two_four_gold_resources_collected_bedwars')
        self.two_four_iron_collected = checkJsonNullValue(eval(json), 'two_four_iron_resources_collected_bedwars')
        self.two_four_items_purchased = checkJsonNullValue(eval(json), 'two_four_items_purchased_bedwars')
        self.two_four_resources_collected = checkJsonNullValue(eval(json), 'two_four_resources_collected_bedwars')
        self.two_four_void_deaths = checkJsonNullValue(eval(json), 'two_four_void_deaths_bedwars')
        self.two_four_wins = checkJsonNullValue(eval(json), 'two_four_wins_bedwars')
        self.two_four_kills = checkJsonNullValue(eval(json), 'two_four_kills_bedwars')
        self.two_four_void_kills = checkJsonNullValue(eval(json), 'two_four_void_kills_bedwars')
        self.two_four_final_kills = checkJsonNullValue(eval(json), 'two_four_final_kills_bedwars')
        self.two_four_void_final_kills = checkJsonNullValue(eval(json), 'two_four_void_final_kills_bedwars')
        self.two_four_beds_broken = checkJsonNullValue(eval(json), 'two_four_beds_broken_bedwars')
        self.two_four_emerald_collected = checkJsonNullValue(eval(json), 'two_four_emerald_resources_collected_bedwars')
        self.two_four_fall_deaths = checkJsonNullValue(eval(json), 'two_four_fall_deaths_bedwars')
        self.two_four_fall_kills = checkJsonNullValue(eval(json), 'two_four_fall_kills_bedwars')
        self.two_four_beds_lost = checkJsonNullValue(eval(json), 'two_four_beds_lost_bedwars')
        self.two_four_fall_final_kills = checkJsonNullValue(eval(json), 'two_four_fall_final_kills_bedwars')
        self.two_four_final_deaths = checkJsonNullValue(eval(json), 'two_four_final_deaths_bedwars')
        self.two_four_void_final_deaths = checkJsonNullValue(eval(json), 'two_four_void_final_deaths_bedwars')
        self.two_four_losses = checkJsonNullValue(eval(json), 'two_four_losses_bedwars')
        self.two_four_fall_final_deaths = checkJsonNullValue(eval(json), 'two_four_fall_final_deaths_bedwars')
        self.two_four_projectile_final_kills = checkJsonNullValue(eval(json), 'two_four_projectile_final_kills_bedwars')
        self.two_four_diamonds_collected = checkJsonNullValue(eval(json), 'two_four_diamond_resources_collected_bedwars')
        self.two_four_projectile_kills = checkJsonNullValue(eval(json), 'two_four_projectile_kills_bedwars')
        self.two_four_permanent_items_purchased = checkJsonNullValue(eval(json), 'two_four_permanent_items_purchased_bedwars')
