#  Copyright (c) 2022 Kokhaviel.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

from utils import checkJsonNullValue


class Duels:

    def __init__(self, json):
        self.games_played = checkJsonNullValue(eval(json), 'games_played_duels')
        self.melee_swings = checkJsonNullValue(eval(json), 'melee_swings')
        self.melee_hits = checkJsonNullValue(eval(json), 'melee_hits')
        self.wins = checkJsonNullValue(eval(json), 'wins')
        self.rounds_played = checkJsonNullValue(eval(json), 'rounds_played')
        self.kills = checkJsonNullValue(eval(json), 'kills')
        self.health_regenerated = checkJsonNullValue(eval(json), 'health_regenerated')
        self.damage_dealt = checkJsonNullValue(eval(json), 'damage_dealt')
        self.recent_plays = checkJsonNullValue(eval(json), 'duels_recently_played')
        self.losses = checkJsonNullValue(eval(json), 'losses')
        self.deaths = checkJsonNullValue(eval(json), 'deaths')
        self.heal_pots_used = checkJsonNullValue(eval(json), 'heal_pots_used')
        self.blitz_duels_kit = checkJsonNullValue(eval(json), 'blitz_duels_kit')
        self.mega_walls_class = checkJsonNullValue(eval(json), 'mw_duels_class')
        self.chat_enabled = checkJsonNullValue(eval(json), 'chat_enabled', 'on')
        self.coins = checkJsonNullValue(eval(json), 'coins')
        self.cosmetics = checkJsonNullValue(eval(json), 'packages')
        self.cosmetic_title = checkJsonNullValue(eval(json), 'active_cosmetictitle')
        self.loot_chests = checkJsonNullValue(eval(json), 'duels_chests')
        self.projectile_trail = checkJsonNullValue(eval(json), 'active_projectile_trail')
        self.emblem = checkJsonNullValue(eval(json), 'active_emblem')
        self.kill_message = checkJsonNullValue(eval(json), 'active_killmessages')
        self.kill_effect = checkJsonNullValue(eval(json), 'active_kill_effect')
        self.victory_dance = checkJsonNullValue(eval(json), 'active_victory_dance')
        self.auras = checkJsonNullValue(eval(json), 'active_auras')
        self.weapon_pack = checkJsonNullValue(eval(json), 'active_weaponpacks')
        self.progress_mode = checkJsonNullValue(eval(json), 'progress_mode')
        self.status = checkJsonNullValue(eval(json), 'status_field')
        self.blocks_placed = checkJsonNullValue(eval(json), 'blocks_placed')
        self.golden_apples_eaten = checkJsonNullValue(eval(json), 'golden_apples_eaten')
        self.goals = checkJsonNullValue(eval(json), 'goals')
        self.hat = checkJsonNullValue(eval(json), 'active_hat')
        self.cage = checkJsonNullValue(eval(json), 'active_cage')
        self.goal = checkJsonNullValue(eval(json), 'active_goal')

        self.uhc_health_regenerated = checkJsonNullValue(eval(json), 'uhc_duel_health_regenerated')
        self.uhc_losses = checkJsonNullValue(eval(json), 'uhc_duel_losses')
        self.uhc_melee_swings = checkJsonNullValue(eval(json), 'uhc_duel_melee_swings')
        self.uhc_rounds_played = checkJsonNullValue(eval(json), 'uhc_duel_rounds_played')
        self.uhc_deaths = checkJsonNullValue(eval(json), 'uhc_duel_deaths')
        self.uhc_damage_dealt = checkJsonNullValue(eval(json), 'uhc_duel_damage_dealt')
        self.uhc_melee_hits = checkJsonNullValue(eval(json), 'uhc_duel_melee_hits')
        self.uhc_bow_shots = checkJsonNullValue(eval(json), 'uhc_duel_bow_shots')
        self.uhc_bow_hits = checkJsonNullValue(eval(json), 'uhc_duel_bow_hits')
        self.uhc_kills = checkJsonNullValue(eval(json), 'uhc_duel_kills')
        self.uhc_wins = checkJsonNullValue(eval(json), 'uhc_duel_wins')
        self.uhc_winstreak = checkJsonNullValue(eval(json), 'current_uhc_winstreak')
        self.best_uhc_winstreak = checkJsonNullValue(eval(json), 'best_uhc_winstreak')
        self.uhc_blocks_placed = checkJsonNullValue(eval(json), 'uhc_duel_blocks_placed')
        self.uhc_golden_apples_eaten = checkJsonNullValue(eval(json), 'uhc_duel_golden_apples_eaten')

        self.skywars_blocks_placed = checkJsonNullValue(eval(json), 'sw_duel_blocks_placed')
        self.skywars_damage_dealt = checkJsonNullValue(eval(json), 'sw_duel_damage_dealt')
        self.skywars_health_regenerated = checkJsonNullValue(eval(json), 'sw_duel_health_regenerated')
        self.skywars_kills = checkJsonNullValue(eval(json), 'sw_duel_kills')
        self.skywars_melee_hits = checkJsonNullValue(eval(json), 'sw_duel_melee_hits')
        self.skywars_melee_swings = checkJsonNullValue(eval(json), 'sw_duel_melee_swings')
        self.skywars_rounds_played = checkJsonNullValue(eval(json), 'sw_duel_rounds_played')
        self.skywars_wins = checkJsonNullValue(eval(json), 'sw_duel_wins')
        self.skywars_bow_hits = checkJsonNullValue(eval(json), 'sw_duel_bow_hits')
        self.skywars_bow_shots = checkJsonNullValue(eval(json), 'sw_duel_bow_shots')
        self.skywars_deaths = checkJsonNullValue(eval(json), 'sw_duel_deaths')
        self.skywars_losses = checkJsonNullValue(eval(json), 'sw_duel_losses')
        self.skywars_winstreak = checkJsonNullValue(eval(json), 'current_skywars_winstreak')
        self.best_skywars_winstreak = checkJsonNullValue(eval(json), 'best_skywars_winstreak')

        self.mega_walls_winstreak = checkJsonNullValue(eval(json), 'current_mega_walls_winstreak')
        self.best_mega_walls_winstreak = checkJsonNullValue(eval(json), 'best_mega_walls_winstreak')
        self.mega_walls_blocks_placed = checkJsonNullValue(eval(json), 'mw_duel_blocks_placed')
        self.mega_walls_bow_hits = checkJsonNullValue(eval(json), 'mw_duel_bow_hits')
        self.mega_walls_bow_shots = checkJsonNullValue(eval(json), 'mw_duel_bow_shots')
        self.mega_walls_damage_dealt = checkJsonNullValue(eval(json), 'mw_duel_damage_dealt')
        self.mega_walls_deaths = checkJsonNullValue(eval(json), 'mw_duel_deaths')
        self.mega_walls_health_regenerated = checkJsonNullValue(eval(json), 'mw_duel_health_regenerated')
        self.mega_walls_losses = checkJsonNullValue(eval(json), 'mw_duel_losses')
        self.mega_walls_melee_hits = checkJsonNullValue(eval(json), 'mw_duel_melee_hits')
        self.mega_walls_melee_swings = checkJsonNullValue(eval(json), 'mw_duel_melee_swings')
        self.mega_walls_rounds_played = checkJsonNullValue(eval(json), 'mw_duel_rounds_played')
        self.mega_walls_kills = checkJsonNullValue(eval(json), 'mw_duel_kills')
        self.mega_walls_wins = checkJsonNullValue(eval(json), 'mw_duel_wins')

        self.blitz_winstreak = checkJsonNullValue(eval(json), 'current_blitz_winstreak')
        self.best_blitz_winstreak = checkJsonNullValue(eval(json), 'best_blitz_winstreak')
        self.blitz_melee_swings = checkJsonNullValue(eval(json), 'blitz_duel_melee_swings')
        self.blitz_damage_dealt = checkJsonNullValue(eval(json), 'blitz_duel_damage_dealt')
        self.blitz_melee_hits = checkJsonNullValue(eval(json), 'blitz_duel_melee_hits')
        self.blitz_rounds_played = checkJsonNullValue(eval(json), 'blitz_duel_rounds_played')
        self.blitz_wins = checkJsonNullValue(eval(json), 'blitz_duel_wins')
        self.blitz_health_regenerated = checkJsonNullValue(eval(json), 'blitz_duel_health_regenerated')
        self.blitz_kills = checkJsonNullValue(eval(json), 'blitz_duel_kills')
        self.blitz_losses = checkJsonNullValue(eval(json), 'blitz_duel_losses')
        self.blitz_deaths = checkJsonNullValue(eval(json), 'blitz_duel_deaths')
        self.blitz_bow_shots = checkJsonNullValue(eval(json), 'blitz_duel_bow_shots')
        self.blitz_bow_hits = checkJsonNullValue(eval(json), 'blitz_duel_bow_hits')
        self.blitz_blocks_placed = checkJsonNullValue(eval(json), 'blitz_duel_blocks_placed')

        self.op_damage_dealt = checkJsonNullValue(eval(json), 'op_duel_damage_dealt')
        self.op_kills = checkJsonNullValue(eval(json), 'op_duel_kills')
        self.op_melee_swings = checkJsonNullValue(eval(json), 'op_duel_melee_swings')
        self.op_melee_hits = checkJsonNullValue(eval(json), 'op_duel_melee_hits')
        self.op_health_regenerated = checkJsonNullValue(eval(json), 'op_duel_health_regenerated')
        self.op_wins = checkJsonNullValue(eval(json), 'op_duel_wins')
        self.op_rounds_played = checkJsonNullValue(eval(json), 'op_duel_rounds_played')
        self.op_deaths = checkJsonNullValue(eval(json), 'op_duel_deaths')
        self.op_losses = checkJsonNullValue(eval(json), 'op_duel_losses')
        self.op_bow_shots = checkJsonNullValue(eval(json), 'op_duel_bow_shots')
        self.op_bow_hits = checkJsonNullValue(eval(json), 'op_duel_bow_hits')
        self.op_winstreak = checkJsonNullValue(eval(json), 'current_op_winstreak')
        self.best_op_winstreak = checkJsonNullValue(eval(json), 'best_op_winstreak')

        self.classic_bow_hits = checkJsonNullValue(eval(json), 'classic_duel_bow_hits')
        self.classic_bow_shots = checkJsonNullValue(eval(json), 'classic_duel_bow_shots')
        self.classic_damage_dealt = checkJsonNullValue(eval(json), 'classic_duel_damage_dealt')
        self.classic_health_regenerated = checkJsonNullValue(eval(json), 'classic_duel_health_regenerated')
        self.classic_melee_hits = checkJsonNullValue(eval(json), 'classic_duel_melee_hits')
        self.classic_melee_swings = checkJsonNullValue(eval(json), 'classic_duel_melee_swings')
        self.classic_rounds_played = checkJsonNullValue(eval(json), 'classic_duel_rounds_played')
        self.best_classic_winstreak = checkJsonNullValue(eval(json), 'best_classic_winstreak')
        self.classic_winstreak = checkJsonNullValue(eval(json), 'current_classic_winstreak')
        self.classic_kills = checkJsonNullValue(eval(json), 'classic_duel_kills')
        self.classic_wins = checkJsonNullValue(eval(json), 'classic_duel_wins')
        self.classic_deaths = checkJsonNullValue(eval(json), 'classic_duel_deaths')
        self.classic_losses = checkJsonNullValue(eval(json), 'classic_duel_losses')

        self.bow_bow_hits = checkJsonNullValue(eval(json), 'bow_duel_bow_hits')
        self.bow_wins = checkJsonNullValue(eval(json), 'bow_duel_wins')
        self.bow_bow_shots = checkJsonNullValue(eval(json), 'bow_duel_bow_shots')
        self.bow_health_regenerated = checkJsonNullValue(eval(json), 'bow_duel_health_regenerated')
        self.bow_kills = checkJsonNullValue(eval(json), 'bow_duel_kills')
        self.bow_damage_dealt = checkJsonNullValue(eval(json), 'bow_duel_damage_dealt')
        self.bow_rounds_played = checkJsonNullValue(eval(json), 'bow_duel_rounds_played')
        self.bow_deaths = checkJsonNullValue(eval(json), 'bow_duel_deaths')
        self.bow_losses = checkJsonNullValue(eval(json), 'bow_duel_losses')
        self.bow_winstreak = checkJsonNullValue(eval(json), 'current_bow_winstreak')
        self.best_bow_winstreak = checkJsonNullValue(eval(json), 'best_bow_winstreak')

        self.no_debuff_winstreak = checkJsonNullValue(eval(json), 'current_no_debuff_winstreak')
        self.best_no_debuff_winstreak = checkJsonNullValue(eval(json), 'best_no_debuff_winstreak')

        self.combo_melee_hits = checkJsonNullValue(eval(json), 'combo_duel_melee_hits')
        self.combo_losses = checkJsonNullValue(eval(json), 'combo_duel_losses')
        self.combo_rounds_played = checkJsonNullValue(eval(json), 'combo_duel_rounds_played')
        self.combo_health_regenerated = checkJsonNullValue(eval(json), 'combo_duel_health_regenerated')
        self.combo_damage_dealt = checkJsonNullValue(eval(json), 'combo_duel_damage_dealt')
        self.combo_deaths = checkJsonNullValue(eval(json), 'combo_duel_deaths')
        self.combo_melee_swings = checkJsonNullValue(eval(json), 'combo_duel_melee_swings')
        self.combo_bow_hits = checkJsonNullValue(eval(json), 'combo_duel_bow_hits')
        self.combo_wins = checkJsonNullValue(eval(json), 'combo_duel_wins')
        self.combo_kills = checkJsonNullValue(eval(json), 'combo_duel_kills')
        self.combo_winstreak = checkJsonNullValue(eval(json), 'current_combo_winstreak')
        self.best_combo_winstreak = checkJsonNullValue(eval(json), 'best_combo_winstreak')
        self.combo_golden_apples_eaten = checkJsonNullValue(eval(json), 'combo_duel_golden_apples_eaten')

        self.sumo_melee_hits = checkJsonNullValue(eval(json), 'sumo_duel_melee_hits')
        self.sumo_melee_swings = checkJsonNullValue(eval(json), 'sumo_duel_melee_swings')
        self.sumo_rounds_played = checkJsonNullValue(eval(json), 'sumo_duel_rounds_played')
        self.sumo_winstreak = checkJsonNullValue(eval(json), 'current_sumo_winstreak')
        self.best_sumo_winstreak = checkJsonNullValue(eval(json), 'best_sumo_winstreak')
        self.sumo_kills = checkJsonNullValue(eval(json), 'sumo_duel_kills')
        self.sumo_wins = checkJsonNullValue(eval(json), 'sumo_duel_wins')
        self.sumo_deaths = checkJsonNullValue(eval(json), 'sumo_duel_deaths')
        self.sumo_losses = checkJsonNullValue(eval(json), 'sumo_duel_losses')

        self.bridge_winstreak = checkJsonNullValue(eval(json), 'current_bridge_winstreak')
        self.best_bridge_winstreak = checkJsonNullValue(eval(json), 'best_bridge_winstreak')
        self.bridge_health_regenerated = checkJsonNullValue(eval(json), 'bridge_duel_health_regenerated')
        self.bridge_goals = checkJsonNullValue(eval(json), 'bridge_duel_goals')
        self.bridge_damage_dealt = checkJsonNullValue(eval(json), 'bridge_duel_damage_dealt')
        self.bridge_melee_hits = checkJsonNullValue(eval(json), 'bridge_duel_melee_hits')
        self.bridge_blocks_placed = checkJsonNullValue(eval(json), 'bridge_duel_blocks_placed')
        self.bridge_melee_swings = checkJsonNullValue(eval(json), 'bridge_duel_melee_swings')
        self.bridge_deaths = checkJsonNullValue(eval(json), 'bridge_duel_deaths')
        self.bridge_kills = checkJsonNullValue(eval(json), 'bridge_duel_kills')
        self.bridge_rounds_played = checkJsonNullValue(eval(json), 'bridge_duel_rounds_played')
        self.bridge_wins = checkJsonNullValue(eval(json), 'bridge_duel_wins')
        self.bridge_bow_shots = checkJsonNullValue(eval(json), 'bridge_duel_bow_shots')
        self.bridge_losses = checkJsonNullValue(eval(json), 'bridge_duel_losses')
        self.bridge_bow_hits = checkJsonNullValue(eval(json), 'bridge_duel_bow_hits')
