#  Copyright (c) 2022 Kokhaviel.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

from utils import checkJsonNullValue


class Skywars:

    def __init__(self, json):
        self.winstreak = checkJsonNullValue(eval(json), 'winstreak')
        self.killstreak = checkJsonNullValue(eval(json), 'killstreak')
        self.highest_killstreak = checkJsonNullValue(eval(json), 'highestKillstreak')
        self.highest_winstreak = checkJsonNullValue(eval(json), 'highestWinstreak')
        self.survived_players = checkJsonNullValue(eval(json), 'survived_players')
        self.losses = checkJsonNullValue(eval(json), 'losses')
        self.deaths = checkJsonNullValue(eval(json), 'deaths')
        self.quits = checkJsonNullValue(eval(json), 'quits')
        self.coins = checkJsonNullValue(eval(json), 'coins')
        self.blocks_broken = checkJsonNullValue(eval(json), 'blocks_broken')
        self.cosmetics = checkJsonNullValue(eval(json), 'packages')
        self.games_played = checkJsonNullValue(eval(json), 'games')
        self.blocks_placed = checkJsonNullValue(eval(json), 'blocks_placed')
        self.kills = checkJsonNullValue(eval(json), 'kills')
        self.egg_thrown = checkJsonNullValue(eval(json), 'egg_thrown')
        self.souls_gathered = checkJsonNullValue(eval(json), 'souls_gathered')
        self.souls = checkJsonNullValue(eval(json), 'souls')
        self.arrows_hit = checkJsonNullValue(eval(json), 'arrows_hit')
        self.arrows_shot = checkJsonNullValue(eval(json), 'arrows_shot')
        self.enderpearls_thrown = checkJsonNullValue(eval(json), 'enderpearls_thrown')
        self.assists = checkJsonNullValue(eval(json), 'assists')
        self.wins = checkJsonNullValue(eval(json), 'wins')
        self.items_enchanted = checkJsonNullValue(eval(json), 'items_enchanted')
        self.soul_well = checkJsonNullValue(eval(json), 'soul_well')
        self.soul_well_rares = checkJsonNullValue(eval(json), 'soul_well_rares')
        self.soul_well_legendaries = checkJsonNullValue(eval(json), 'soul_well_legendaries')
        self.paid_souls = checkJsonNullValue(eval(json), 'paid_souls')
        self.cage = checkJsonNullValue(eval(json), 'activeCage', 'DEFAULT')
        self.chests_opened = checkJsonNullValue(eval(json), 'chests_opened')
        self.time_played = checkJsonNullValue(eval(json), 'time_played')
        self.most_kills = checkJsonNullValue(eval(json), 'most_kills_game')
        self.longest_bow_shot = checkJsonNullValue(eval(json), 'longest_bow_shot')
        self.fastest_win = checkJsonNullValue(eval(json), 'fastest_win')
        self.melee_kills = checkJsonNullValue(eval(json), 'melee_kills')
        self.mob_kills = checkJsonNullValue(eval(json), 'mob_kills')
        self.last_mode = checkJsonNullValue(eval(json), 'lastMode', 'NONE')
        self.projectile_trail = checkJsonNullValue(eval(json), 'activeProjectileTrail', 'DEFAULT')
        self.victory_dance = checkJsonNullValue(eval(json), 'activeVictoryDance', 'DEFAULT')
        self.kill_effect = checkJsonNullValue(eval(json), 'activeKillEffect', 'DEFAULT')
        self.longest_bow_kill = checkJsonNullValue(eval(json), 'longest_bow_kill')
        self.tokens = checkJsonNullValue(eval(json), 'cosmetic_tokens')
        self.death_cry = checkJsonNullValue(eval(json), 'active_deathcry',  'DEFAULT')
        self.bow_kills = checkJsonNullValue(eval(json), 'bow_kills')
        self.spray = checkJsonNullValue(eval(json), 'active_sprays', 'DEFAULT')
        self.balloon = checkJsonNullValue(eval(json), 'active_balloon', 'DEFAULT')
        self.experience = checkJsonNullValue(eval(json), 'skywars_experience')
        self.prestige_icon = checkJsonNullValue(eval(json), 'selected_prestige_icon', 'DEFAULT')
        self.angel_death_level = checkJsonNullValue(eval(json), 'angel_of_death_level')
        self.opals = checkJsonNullValue(eval(json), 'opals')
        self.shard = checkJsonNullValue(eval(json), 'shard')
        self.fall_kills = checkJsonNullValue(eval(json), 'fall_kills')

        self.survived_players_solo = checkJsonNullValue(eval(json), 'survived_players_solo')
        self.deaths_solo_normal = checkJsonNullValue(eval(json), 'deaths_solo_normal')
        self.losses_solo = checkJsonNullValue(eval(json), 'losses_solo')
        self.losses_solo_normal = checkJsonNullValue(eval(json), 'losses_solo_normal')
        self.deaths_solo = checkJsonNullValue(eval(json), 'deaths_solo')
        self.kills_solo_normal = checkJsonNullValue(eval(json), 'kills_solo_normal')
        self.kills_solo = checkJsonNullValue(eval(json), 'kills_solo')
        self.games_solo = checkJsonNullValue(eval(json), 'games_solo')
        self.losses_solo_insane = checkJsonNullValue(eval(json), 'losses_solo_insane')
        self.deaths_solo_insane = checkJsonNullValue(eval(json), 'deaths_solo_insane')
        self.kills_solo_insane = checkJsonNullValue(eval(json), 'kills_solo_insane')
        self.solo_killstreak = checkJsonNullValue(eval(json), 'killstreak_solo')
        self.wins_solo_insane = checkJsonNullValue(eval(json), 'wins_solo_insane')
        self.solo_winstreak = checkJsonNullValue(eval(json), 'winstreak_solo')
        self.wins_solo = checkJsonNullValue(eval(json), 'wins_solo')
        self.assists_solo = checkJsonNullValue(eval(json), 'assists_solo')
        self.solo_kit = checkJsonNullValue(eval(json), 'activeKit_SOLO', 'DEFAULT')
        self.wins_solo_normal = checkJsonNullValue(eval(json), 'wins_solo_normal')
        self.chests_opened_solo = checkJsonNullValue(eval(json), 'chests_opened_solo')
        self.time_played_solo = checkJsonNullValue(eval(json), 'time_played_solo')
        self.most_kills_solo = checkJsonNullValue(eval(json), 'most_kills_game_solo')
        self.void_kills_solo = checkJsonNullValue(eval(json), 'void_kills_solo')
        self.longest_bow_shot_solo = checkJsonNullValue(eval(json), 'longest_bow_shot_solo')
        self.arrows_hit_solo = checkJsonNullValue(eval(json), 'arrows_hit_solo')
        self.arrows_shot_solo = checkJsonNullValue(eval(json), 'arrows_shot_solo')
        self.fastest_win_solo = checkJsonNullValue(eval(json), 'fastest_win_solo')
        self.melee_kills_solo = checkJsonNullValue(eval(json), 'melee_kills_solo')
        self.mob_kills_solo = checkJsonNullValue(eval(json), 'mob_kills_solo')
        self.bow_kills_solo = checkJsonNullValue(eval(json), 'bow_kills_solo')
        self.longest_bow_kill_solo = checkJsonNullValue(eval(json), 'longest_bow_kill_solo')
        self.fall_kills_solo = checkJsonNullValue(eval(json), 'fall_kills_solo')

        self.fastest_win_team = checkJsonNullValue(eval(json), 'fastest_win_team')
        self.deaths_team_normal = checkJsonNullValue(eval(json), 'deaths_team_normal')
        self.losses_team_normal = checkJsonNullValue(eval(json), 'losses_team_normal')
        self.deaths_team = checkJsonNullValue(eval(json), 'deaths_team')
        self.survived_players_team = checkJsonNullValue(eval(json), 'survived_players_team')
        self.losses_team = checkJsonNullValue(eval(json), 'losses_team')
        self.games_played_team = checkJsonNullValue(eval(json), 'games_team')
        self.deaths_team_insane = checkJsonNullValue(eval(json), 'deaths_team_insane')
        self.losses_team_insane = checkJsonNullValue(eval(json), 'losses_team_insane')
        self.assists_team = checkJsonNullValue(eval(json), 'assists_team')
        self.wins_team_insane = checkJsonNullValue(eval(json), 'wins_team_insane')
        self.wins_team = checkJsonNullValue(eval(json), 'wins_team')
        self.winstreak_team = checkJsonNullValue(eval(json), 'winstreak_team')
        self.team_kit = checkJsonNullValue(eval(json), 'activeKit_TEAM', 'DEFAULT')
        self.wins_team_normal = checkJsonNullValue(eval(json), 'wins_team_normal')
        self.kills_team_insane = checkJsonNullValue(eval(json), 'kills_team_insane')
        self.kills_team = checkJsonNullValue(eval(json), 'kills_team')
        self.killstreak_team = checkJsonNullValue(eval(json), 'killstreak_team')
        self.kills_team_normal = checkJsonNullValue(eval(json), 'kills_team_normal')
        self.melee_kills_team = checkJsonNullValue(eval(json), 'melee_kills_team')
        self.most_kills_team = checkJsonNullValue(eval(json), 'most_kills_game_team')
        self.chests_opened_team = checkJsonNullValue(eval(json), 'chests_opened_team')
        self.time_played_team = checkJsonNullValue(eval(json), 'time_played_team')
        self.longest_bow_shot_team = checkJsonNullValue(eval(json), 'longest_bow_shot_team')
        self.arrows_shot_team = checkJsonNullValue(eval(json), 'arrows_shot_team')
        self.arrows_hit_team = checkJsonNullValue(eval(json), 'arrows_hit_team')
        self.void_kills_team = checkJsonNullValue(eval(json), 'void_kills_team')
        self.mob_kills_team = checkJsonNullValue(eval(json), 'mob_kills_team')
        self.longest_bow_kill_team = checkJsonNullValue(eval(json), 'longest_bow_kill_team')
        self.bow_kills_team = checkJsonNullValue(eval(json), 'bow_kills_team')
        self.heads_team = checkJsonNullValue(eval(json), 'heads_team')
        self.fall_kills_team = checkJsonNullValue(eval(json), 'fall_kills_team')

        self.bow_kills_ranked = checkJsonNullValue(eval(json), 'bow_kills_ranked')
        self.longest_bow_kill_ranked = checkJsonNullValue(eval(json), 'longest_bow_kill_ranked')
        self.mob_kills_ranked = checkJsonNullValue(eval(json), 'mob_kills_ranked')
        self.longest_bow_shot_ranked = checkJsonNullValue(eval(json), 'longest_bow_shot_ranked')
        self.arrows_hit_ranked = checkJsonNullValue(eval(json), 'arrows_hit_ranked')
        self.ranked_kit = checkJsonNullValue(eval(json), 'activeKit_RANKED', 'DEFAULT')
        self.arrows_shot_ranked = checkJsonNullValue(eval(json), 'arrows_shot_ranked')
        self.games_played_ranked = checkJsonNullValue(eval(json), 'games_ranked')
        self.deaths_ranked = checkJsonNullValue(eval(json), 'deaths_ranked')
        self.losses_ranked = checkJsonNullValue(eval(json), 'losses_ranked')
        self.survived_players_ranked = checkJsonNullValue(eval(json), 'survived_players_ranked')
        self.chests_opened_ranked = checkJsonNullValue(eval(json), 'chests_opened_ranked')
        self.time_played_ranked = checkJsonNullValue(eval(json), 'time_played_ranked')
        self.kills_ranked = checkJsonNullValue(eval(json), 'kills_ranked')
        self.void_kills_ranked = checkJsonNullValue(eval(json), 'void_kills_ranked')
        self.most_kills_game_ranked = checkJsonNullValue(eval(json), 'most_kills_game_ranked')
        self.melee_kills_ranked = checkJsonNullValue(eval(json), 'melee_kills_ranked')
        self.assists_ranked = checkJsonNullValue(eval(json), 'assists_ranked')
        self.fastest_win_ranked = checkJsonNullValue(eval(json), 'fastest_win_ranked')
        self.winstreak_ranked = checkJsonNullValue(eval(json), 'winstreak_ranked')
        self.killstreak_ranked = checkJsonNullValue(eval(json), 'killstreak_ranked')
        self.wins_ranked = checkJsonNullValue(eval(json), 'wins_ranked')
        self.fall_kills_ranked = checkJsonNullValue(eval(json), 'fall_kills_ranked')

        self.mega_kit = checkJsonNullValue(eval(json), 'activeKit_MEGA', 'DEFAULT')
        self.deaths_mega = checkJsonNullValue(eval(json), 'deaths_mega')
        self.survived_players_mega = checkJsonNullValue(eval(json), 'survived_players_mega')
        self.losses_mega = checkJsonNullValue(eval(json), 'losses_mega')
        self.kills_mega = checkJsonNullValue(eval(json), 'kills_mega')
        self.assists_mega = checkJsonNullValue(eval(json), 'assists_mega')
        self.games_played_mega = checkJsonNullValue(eval(json), 'games_mega')
        self.winstreak_mega = checkJsonNullValue(eval(json), 'winstreak_mega')
        self.wins_mega = checkJsonNullValue(eval(json), 'wins_mega')
        self.longest_bow_kill_mega = checkJsonNullValue(eval(json), 'longest_bow_kill_mega')
        self.bow_kills_mega = checkJsonNullValue(eval(json), 'bow_kills_mega')
        self.fall_kills_mega = checkJsonNullValue(eval(json), 'fall_kills_mega')
        self.chests_opened_mega = checkJsonNullValue(eval(json), 'chests_opened_mega')
        self.most_kills_game_mega = checkJsonNullValue(eval(json), 'most_kills_game_mega')
        self.melee_kills_mega = checkJsonNullValue(eval(json), 'melee_kills_mega')
        self.time_played_mega = checkJsonNullValue(eval(json), 'time_played_mega')
        self.longest_bow_shot_mega = checkJsonNullValue(eval(json), 'longest_bow_shot_mega')
        self.arrows_shot_mega = checkJsonNullValue(eval(json), 'arrows_shot_mega')
        self.arrows_hit_mega = checkJsonNullValue(eval(json), 'arrows_hit_mega')
        self.void_kills_mega = checkJsonNullValue(eval(json), 'void_kills_mega')
        self.fastest_win_mega = checkJsonNullValue(eval(json), 'fastest_win_mega')
        self.mob_kills_mega = checkJsonNullValue(eval(json), 'mob_kills_mega')
        self.killstreak_mega = checkJsonNullValue(eval(json), 'killstreak_mega')

        self.fastest_win_lab_solo = checkJsonNullValue(eval(json), 'fastest_win_lab_solo')
        self.survived_players_lab_team = checkJsonNullValue(eval(json), 'survived_players_lab_team')
        self.chests_opened_lab_team = checkJsonNullValue(eval(json), 'chests_opened_lab_team')
        self.time_played_lab_team = checkJsonNullValue(eval(json), 'time_played_lab_team')
        self.deaths_lab = checkJsonNullValue(eval(json), 'deaths_lab')
        self.time_played_lab = checkJsonNullValue(eval(json), 'time_played_lab')
        self.assists_lab_team = checkJsonNullValue(eval(json), 'assists_lab_team')
        self.survived_players_lab = checkJsonNullValue(eval(json), 'survived_players_lab')
        self.coins_gained_lab = checkJsonNullValue(eval(json), 'coins_gained_lab')
        self.chests_opened_lab = checkJsonNullValue(eval(json), 'chests_opened_lab')
        self.assists_lab = checkJsonNullValue(eval(json), 'assists_lab')
        self.losses_lab_team = checkJsonNullValue(eval(json), 'losses_lab_team')
        self.losses_lab = checkJsonNullValue(eval(json), 'losses_lab')
        self.quits_lab = checkJsonNullValue(eval(json), 'quits_lab')
        self.enderpearls_thrown_lab = checkJsonNullValue(eval(json), 'enderpearls_thrown_lab')
        self.deaths_lab_team = checkJsonNullValue(eval(json), 'deaths_lab_team')
        self.wins_lab = checkJsonNullValue(eval(json), 'wins_lab')
        self.killstreak_lab = checkJsonNullValue(eval(json), 'killstreak_lab')
        self.void_kills_lab = checkJsonNullValue(eval(json), 'void_kills_lab')
        self.souls_gathered_lab = checkJsonNullValue(eval(json), 'souls_gathered_lab')
        self.games_played_lab = checkJsonNullValue(eval(json), 'games_lab')
        self.kills_lab = checkJsonNullValue(eval(json), 'kills_lab')
        self.winstreak_lab = checkJsonNullValue(eval(json), 'winstreak_lab')
        self.melee_kills_lab_team = checkJsonNullValue(eval(json), 'melee_kills_lab_team')
        self.kills_lab_team = checkJsonNullValue(eval(json), 'kills_lab_team')
        self.winstreak_lab_team = checkJsonNullValue(eval(json), 'winstreak_lab_team')
        self.games_played_lab_team = checkJsonNullValue(eval(json), 'games_lab_team')
        self.killstreak_lab_team = checkJsonNullValue(eval(json), 'killstreak_lab_team')
        self.melee_kills_lab = checkJsonNullValue(eval(json), 'melee_kills_lab')
        self.wins_lab_team = checkJsonNullValue(eval(json), 'wins_lab_team')
        self.souls_lab = checkJsonNullValue(eval(json), 'souls_lab')
        self.void_kills_lab_team = checkJsonNullValue(eval(json), 'void_kills_lab_team')
        self.blocks_broken_lab = checkJsonNullValue(eval(json), 'blocks_broken_lab')
        self.fastest_win_lab_team = checkJsonNullValue(eval(json), 'fastest_win_lab_team')
        self.fastest_win_lab = checkJsonNullValue(eval(json), 'fastest_win_lab')
        self.egg_thrown_lab = checkJsonNullValue(eval(json), 'egg_thrown_lab')
        self.survived_players_lab_solo = checkJsonNullValue(eval(json), 'survived_players_lab_solo')
        self.losses_lab_solo = checkJsonNullValue(eval(json), 'losses_lab_solo')
        self.melee_kills_lab_solo = checkJsonNullValue(eval(json), 'melee_kills_lab_solo')
        self.kills_lab_solo = checkJsonNullValue(eval(json), 'kills_lab_solo')
        self.chests_opened_lab_solo = checkJsonNullValue(eval(json), 'chests_opened_lab_solo')
        self.deaths_lab_solo = checkJsonNullValue(eval(json), 'deaths_lab_solo')
        self.time_played_lab_solo = checkJsonNullValue(eval(json), 'time_played_lab_solo')
        self.games_lab_solo = checkJsonNullValue(eval(json), 'games_lab_solo')
        self.winstreak_lab_solo = checkJsonNullValue(eval(json), 'winstreak_lab_solo')
        self.killstreak_lab_solo = checkJsonNullValue(eval(json), 'killstreak_lab_solo')
        self.wins_lab_solo = checkJsonNullValue(eval(json), 'wins_lab_solo')
        self.void_kills_lab_solo = checkJsonNullValue(eval(json), 'void_kills_lab_solo')
        self.blocks_placed_lab = checkJsonNullValue(eval(json), 'blocks_placed_lab')
        self.assists_lab_solo = checkJsonNullValue(eval(json), 'assists_lab_solo')
        self.arrows_shot_lab_solo = checkJsonNullValue(eval(json), 'arrows_shot_lab_solo')
        self.arrows_shot_lab = checkJsonNullValue(eval(json), 'arrows_shot_lab')
        self.arrows_hit_lab_team = checkJsonNullValue(eval(json), 'arrows_hit_lab_team')
        self.arrows_shot_lab_team = checkJsonNullValue(eval(json), 'arrows_shot_lab_team')
        self.arrows_hit_lab = checkJsonNullValue(eval(json), 'arrows_hit_lab')
        self.mob_kills_lab_team = checkJsonNullValue(eval(json), 'mob_kills_lab_team')
        self.mob_kills_lab = checkJsonNullValue(eval(json), 'mob_kills_lab')
        self.longest_bow_shot_lab = checkJsonNullValue(eval(json), 'longest_bow_shot_lab')
        self.longest_bow_shot_lab_team = checkJsonNullValue(eval(json), 'longest_bow_shot_lab_team')
        self.arrows_hit_lab_solo = checkJsonNullValue(eval(json), 'arrows_hit_lab_solo')
        self.longest_bow_shot_lab_solo = checkJsonNullValue(eval(json), 'longest_bow_shot_lab_solo')
        self.mob_kills_lab_solo = checkJsonNullValue(eval(json), 'mob_kills_lab_solo')
        self.bow_kills_lab = checkJsonNullValue(eval(json), 'bow_kills_lab')
        self.bow_kills_lab_solo = checkJsonNullValue(eval(json), 'bow_kills_lab_solo')
        self.shard_lab = checkJsonNullValue(eval(json), 'shard_lab')
        self.fall_kills_lab = checkJsonNullValue(eval(json), 'fall_kills_lab')
        self.fall_kills_lab_solo = checkJsonNullValue(eval(json), 'fall_kills_lab_solo')

        self.heads = checkJsonNullValue(eval(json), 'heads')
        self.heads_eww = checkJsonNullValue(eval(json), 'heads_eww')
        self.heads_solo = checkJsonNullValue(eval(json), 'heads_solo')
        self.heads_tasty = checkJsonNullValue(eval(json), 'heads_tasty')
        self.heads_divine = checkJsonNullValue(eval(json), 'heads_divine')
        self.heads_succulent = checkJsonNullValue(eval(json), 'heads_succulent')
        self.heads_yucky = checkJsonNullValue(eval(json), 'heads_yucky')
        self.heads_salty = checkJsonNullValue(eval(json), 'heads_salty')
        self.heads_decent = checkJsonNullValue(eval(json), 'heads_decent')
        self.heads_meh = checkJsonNullValue(eval(json), 'heads_meh')
        self.heads_heavenly = checkJsonNullValue(eval(json), 'heads_heavenly')
        self.heads_sweet = checkJsonNullValue(eval(json), 'heads_sweet')


